name    'saz-ntp'
version '2.0.3'
source 'UNKNOWN'
author 'saz'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'Manage NTP via puppet'
project_page 'https://github.com/saz/puppet-ntp'
